package:
  name: mcce
  version: "1.0.0"

source:
  git_url: https://github.com/newbooks/Stable-MCCE.git
  git_tag: mcce-conda


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - xlrd
    - openpyxl
    - requests

about:
  home: https://gunnerlab.github.io/Stable-MCCE/
  license: MIT
