package:
  name: mcce
  # fixed ntg.ftpl
  version: "1.0.8"

  # Past versions
  # version: "1.0.6"
  # version: "1.0.7" fixed diff_mc.py, print nothing instead of error when mismatch, fixed fort38_distance.py, allow list2 longer than list1

source:
  git_url: https://github.com/newbooks/Stable-MCCE.git
  git_tag: mcce-conda


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - xlrd
    - openpyxl
    - requests

about:
  home: https://gunnerlab.github.io/Stable-MCCE/
  license: MIT
